# Generated by Django 5.2.12 on 2026-03-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('IPL', 'IPL'), ('World Cup', 'World Cup'), ('Player', 'Player')], default='IPL', max_length=50),
        ),
    ]
